### ISSUE TITLE
store test results as well as coverage

### ISSUE THREAD

**Issue by jimhester** [r-lib/covr#144]
Simply include all objects from the environment the test were run in.

**Comment by kforner** [comment]
Yes !

**Comment by brodieG** [comment]
In addition to objects, it would be useful if the [tmp_lib](https://github.com/jimhester/covr/blob/master/R/covr.R#L221) location is returned as well so that test output can be inspected (e.g. *.Rout.fail).  As far as I can tell the only way to get to those files now is to `debug` `package_coverage`, capture the `tmp_lib` value, and then use that after `package_coverage` completes for review.

**Comment by jimhester** [comment]
I don't think we really need `tmp_lib`. The way I generally do this is run with `package_coverage(clean = FALSE)` then look in `tempdir()`, it is easy to see which directory within `tempdir()` was created last.

**Comment by brodieG** [comment]
Would it be worth my submitting a PR that documents this method?

Also, as an aside, I thought about mentioning that `clean=TRUE` should probably remove `tmp_lib` and its contents, but I don't think it does currently.  So right now you can get to the file whether you set `clean=FALSE` or not.  If this is not intended behavior (as suggested by your comment), I can submit a PR for that as well (or make an issue for the record, if you prefer).

Either way, not a big deal.

**Comment by jimhester** [comment]
`clean = TRUE` now removes `tmp_lib` and if `clean = FALSE` the library path is added to the coverage object as a 'library' attribute.

This would allow you to use `clean = FALSE` and inspect the test output files in `tmp_lib/pkgname` if desired.

We cannot save the outputs in an object due to the way that the test files are run now; so I think this is the best that can be done.
