### ISSUE TITLE
Failed to upload coverage data. Reply by Coveralls: Build processing error for coveralls

### ISSUE THREAD

**Issue by kush99993s** [r-lib/covr#285]
I am passing following arguments:

    after_success:
       - Rscript -e "covr::coveralls(repo_token= 'xxxx', service_name = 'travis-pro')"

However, it is throwing error as follows:
Failed to upload coverage data. Reply by Coveralls: Build processing error.   I have ran following command, and i get result.

`z <- package_coverage()`. So, I don't know why it is failing 

When I run following command I get json, however,  it contain whole file including Roxygen2 comments and function and also coverage information. I don't know if it is right or wrong.

Example:

```
xx = to_coveralls(coverage, repo_token = repo_token, service_name = service)
print(xx)
```

It return following json response:

> {"repo_token":"xxxxx","source_files":[{"name":"R/testFunct.R","source":"#' @title Function for testFunct @param_id ... testFunct <- function(\n  param_id ...}

**Comment by jimhester** [comment]
I unfortunately have not used coveralls on private repositories, so cannot offer any advice here. The JSON for coveralls does contain the source code of the files, so that is not a surprise.

**Comment by kiwiroy** [comment]
I think that the test at https://github.com/r-lib/covr/blob/749652849c1379719e40121103d3655d0796e676/tests/testthat/test-coveralls.R#L90 is wrong based on the **required** status of `service_name` in [API ref](https://docs.coveralls.io/api-reference).

The `git` data needs to be a hash 
https://github.com/r-lib/covr/blob/749652849c1379719e40121103d3655d0796e676/R/coveralls.R#L78

There should also be a `source_digest` per file and the `service_name` is required for *travis-pro* otherwise some kind of mix up can occur between job processing.
