### ISSUE TITLE
Zero coverage

### ISSUE THREAD

**Issue by Fazendaaa** [r-lib/covr#338]
Infos:
* OS: Arch Linux
* R: 3.5.1

Right now I'm developing the following package to learn R

https://github.com/Fazendaaa/project-euler/tree/master/src/r

The funny thing is that even with just two simple R files, that both passes all of the test.*.R files, covr seems to not get the coverage right; giving me 0% of coverage on both of them.

So far I've tried using report() call at the end of the test.*.R files, testing in the REPL through package_coverage() and report().

Those are pretty simple source files, If anyone could point me out the error, would mean a lot to me.

**Comment by jimhester** [comment]
Your testthat test are not structured properly, in particular you are missing a `test/testthat.R` file in the `tests/` directory. Rather than setting this up by hand (which is error prone as you have discovered) I would recommend using `usethis::use_testthat()` and `usethis::use_test()`, which automatically sets this up correctly.

**Comment by Fazendaaa** [comment]
Thanks, that helped me out. Right now I'm having another issue, but I think that this might be a testthat issue.

**Comment by Fazendaaa** [comment]
The problem is that I also have o set my ```assertthat``` in tests/testthat.R. Already fixed.
