### ISSUE TITLE
covr missing lines that are ostensibly tested

### ISSUE THREAD

**Issue by MichaelChirico** [r-lib/covr#346]
`report()` for [`geohashTools`](https://github.com/MichaelChirico/geohashTools) shows some lines uncovered that I explicitly set out to cover...

(ditto Codecov [here](https://codecov.io/gh/MichaelChirico/geohashTools))

The easiest to see without diving too deep into package internals would be here:

https://codecov.io/gh/MichaelChirico/geohashTools/src/master/src/geohash.cpp#L339

This is covered by two tests (and `R CMD check` is passing) here:

https://github.com/MichaelChirico/geohashTools/blob/master/tests/testthat/test-encode.R#L61-L62

Am I missing something, or should that line be counted as covered?

(There are a few other cases that are definitely covered -- I tried replacing some of those "uncovered" lines with `stop("cursed error");` and re-installing, at which point tests started failing)

**Comment by oganm** [comment]
I have a similar issue. [This](https://github.com/oganm/homologene/blob/master/R/autoTranslate.R) file is tested in the same file with everything else [here](https://github.com/oganm/homologene/blob/master/tests/testthat/test_homologene.R#L22-L44) yet [codecov claims](https://codecov.io/gh/oganm/homologene/src/master/R/autoTranslate.R) no coverage of the file at all.

**Comment by jimhester** [comment]
@oganm Your test is not running, testthat tests need to be prefixed with `test-` not `test_`.

**Comment by jimhester** [comment]
@MichaelChirico To debug what is going on you can try running `covr::package_coverage(quiet = FALSE, clean = FALSE)` and looking at the `*.gcov` file in your `src/` directory to see if you see the same lack of coverage in the gcov output or not.

**Comment by oganm** [comment]
@jimhester As far as I know they only have to start with "test" as described [here](http://r-pkgs.had.co.nz/tests.html). The next character shouldn't matter.

Also a portion of the tests do seem to run as I end up with 47% coverage instead of 0 since all tests are in the same file. And when I do `devtools::test()` I see all 12 `expect_` functions return OK in the report.

Finally changing the file name also does not change the output of `pacakge_coverage('.')` which is 47% in both cases

**Comment by oganm** [comment]
The original example I gave in my comment somehow works now but the same package still has issues with assessing coverage correctly, now with different functions. I had coverage change due to seemingly unrelated changes before.

In the current repo, [here](https://github.com/oganm/homologene/blob/master/tests/testthat/test_diopt.R) the funcion `diopt` is tested, running `devtools::test()` really runs said test, yet I get [0 coverage](https://codecov.io/gh/oganm/homologene/src/master/R/diopt.R).

**Comment by jimhester** [comment]
You have a test that is detaching the package, which is why the coverage is not being reported correctly, removing this (unneeded) test fixes the issue https://github.com/oganm/homologene/pull/13
