### ISSUE TITLE
Differences between covr and devtools::test

### ISSUE THREAD

**Issue by llrs** [r-lib/covr#362]
I have a package at ([llrs/RGCCA](https://github.com/llrs/RGCCA/tree/37de8cf7b84d55773d48957feb3b7b34744963b5)) that passes all the tests with `devtools::test()` but not with `covr::package_coverage()`

```
> covr::package_coverage()
Error: Failure in `/tmp/RtmptfdmJk/R_LIBS19697a576246/RGCCA/RGCCA-tests/testthat.Rout.fail`
est-sgcca.R#13) 
3. Error: horst (@test-sgcca.R#74) 
4. Error: factorial (@test-sgcca.R#132) 

Error: testthat unit tests failed
Execution halted
```

Also I tried to access the temporary file but I couldn't (the R_LIBS19697a576246 folder does not exists).

Is there anything I can do?

**Comment by jimhester** [comment]
You did not register the S3 methods for the shaving generic. This was working with `devtools::test()` because of lexical S3 registration, but would not work when the package was loaded normally nor in `R CMD check`.

It is always best when seeing differences with covr to verify the behavior with `R CMD check`, `devtools::test()` is only an approximation of how the code is loaded and tests are actually run.

**Comment by llrs** [comment]
Thanks for the advice I will follow from now on and your quick response.
