### ISSUE TITLE
Skip inserting covr::count() on specified lines

### ISSUE THREAD

**Issue by mjskay** [r-lib/covr#381]
Is it possible to tell covr not to insert `covr::count()` into particular lines (or to add this functionality)?

We've encountered this problem on a package we are developing that does some code generation. Because `covr::count()` is inserted into some of the generated unevaluated expressions, tests that don't break with `devtools::test()` can break with `covr::package_coverage()`. For example, given a function like this:

```r
break_covr = function() {
  quote({ x <- 5 })
}
```

The following test will pass on `devtools::test()` and break on `covr::package_coverage()`:

```r
test_that("covr breaks", {
  expect_equal(break_covr(), quote({ x <- 5 }))
})
```

I believe this is because `covr` inserts a `covr::count` call into the quoted expression, so they are no longer equal. It might be nice to have a way to tell covr not to do that for particular lines, e.g.:

```r
break_covr = function() {
  quote({ x <- 5 })   # nocount
}
```

Or something like that (or to have the existing `#nocov` comment do that?)

Currently we are using a workaround like this, which works but is kind of ugly:

```r
break_covr = function() {
  call("{", quote(x <- 5))
}
```

**Comment by jimhester** [comment]
No there is really no way currently to do this, in the next version of testthat there will be a [`skip_on_covr()` function](https://github.com/r-lib/testthat/pull/895/files#diff-8118c4bf22b8b996a3b1d49ba32e01feR190-R196) so that you can skip tests like this that have different behavior.

You could define that function inline in your package in the meantime.

**Comment by mjskay** [comment]
Great, thanks!
