### ISSUE TITLE
S3 methods registered with `.S3method()` are not covered

### ISSUE THREAD

**Issue by wlandau** [r-lib/covr#431]
@lionel- recently advised me to start using `.S3method()` or namespace directives for S3 instead of the infamous dot syntax. When I made the transition in a package, `covr` stopped covering the methods.

I posted an example to https://github.com/wlandau/covrtest/commits/s3. It has a minimal R script

```r
f <- function(x){
  UseMethod("f")
}

f_character <- function(x) {
  nchar(x)
}

.S3method("f", "character", f_character)
```

and a test that should cover everything.

```r
test_that("f works", {
  expect_equal(f("abc"), 3L)
})
```

But package coverage shows:

```r
covrtest Coverage: 50.00%
R/f.R: 50.00%
  filename   functions line value
2    R/f.R f_character    6     0
```

**Comment by lionel-** [comment]
You need to register in the onLoad hook, otherwise it only happens at build time. Not sure this explains the coverage loss though.

By the way I would still use the dot syntax with roxygen's `@export`, which creates the appropriate namespace directive. Note that roxygen doesn't actually export the method, so the dot syntax is not used for dispatch in that case. R CMD check would warn if you only exported but did not register the method in NAMESPACE anyway.

`.S3method()` is only useful for scripts or for lazy registration (to avoid dependencies etc). But then I would copy `vctrs::s3_register()` in my namespace, this way I don't depend on a recent version of R.

**Comment by jimhester** [comment]
The tracing code is added by covr during `.onLoad()`, but your call to `.S3method` occurs during install time, so the function that is registered does not have any tracing calls.

If you do the following you will see `f_character` is covered.

```r
.onLoad <- function(...) {
  .S3method("f", "character", f_character)
}
```

But also I agree with @lionel-, you should use these runtime registrations only in exceptional circumstances. The vast majority of the time it is better to register S3 methods in the NAMESPACE file, e.g. by using the dot syntax with `#' @export`.

**Comment by wlandau** [comment]
Thank you both, I will stick with the dot syntax and use `#' @export`.
