### ISSUE TITLE
`covr::codecov()` times out on GHA occasionally

### ISSUE THREAD

**Issue by pat-s** [r-lib/covr#435]
I am using `covr::codecov()` in 30+ repos daily and occasionally I see upload timeouts as in https://github.com/mlr-org/mlr3misc/runs/737104888?check_suite_focus=true#step:16:167.

This is quite annoying since it may happen multiple times a day, drawing attention to the build for no reason.

Is this within the scope of {covr} or {httr}? Or completely off to GHA?

**Comment by jimhester** [comment]
I am not sure there is a lot we can do, though potentially https://github.com/r-lib/covr/pull/428 might help the situation by retrying the upload.

One thing you _could_ do is use the equivalent of `Rscript -e 'covr::codevov()' || true` so that even if the covr upload fails the step still turns a success exit status.

**Comment by pat-s** [comment]
Thanks. Enforcing {covr} dev for now and observing how that goes.
